### ISSUE TITLE
[Update] 배포 시 변경이 필요한 환경 설정 변경

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#100]
# 작업 내용
이슈번호 : #100

## TODO
- [x] 데이터베이스 이름 변경
- [x] Debug모드 환경 변수 설정
- [x] ALLOWED_HOSTS 환경 변수 설정
