### ISSUE TITLE
[Feature] AWS S3와 연동 부분 추가

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#102]
# 작업 내용
이슈번호 : #102

## TODO
- [x] Settings.py AWS-S3 연결 부 추가 [ .env에 USE_S3 의 값 조정을 통해 사용 여부 결정 ]
- [x] 연동에 필요한 라이브러리 설치
- [x] 미디어 파일 연결을 위한 파일 추가
