### ISSUE TITLE
[Update] 채팅의 기능의 추가 및 구조 변경으로 전면 수정

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#111]
# 작업 내용
이슈번호 : #31 

## TODO
- [x] 1:1채팅만 지원하기 때문에 모델 축소
- [x] 사용자 및 어드민이 채팅방을 읽었는지 표기하기 위한 필드 추가
- [x]  이로인한 테스트코드 전면 수정
