### ISSUE TITLE
[Feature] 카카오 소셜로그인 구현 

### ISSUE THREAD

**Issue by Soeun-Jang** [Songjimyung/EcoCanvas-Backend#12]
# 작업 내용
이슈번호 : #12

## TODO
- [ ] 카카오 developer에서 API Key 발급받기
- [ ] 플랫폼 설정(사이트 도메인, Redirect URI 등록)
- [ ] 로그인
- [ ] redirect 호출
- [ ] JWT 발급 받기
