### ISSUE TITLE
[Test] user 테스트 코드 추가 작성

### ISSUE THREAD

**Issue by JooHan10** [Songjimyung/EcoCanvas-Backend#120]
# 작업 내용
이슈번호 : #120

## TODO
- [x] 회원정보 수정 테스트 코드 작성
- [x] 회원 비활성화 테스트 코드 작성
- [x]  비밀번호 수정
- [x]  비밀번호 찾기(재설정)
