### ISSUE TITLE
[Feature] 구글 소셜로그인 구현

### ISSUE THREAD

**Issue by Soeun-Jang** [Songjimyung/EcoCanvas-Backend#13]
# 작업 내용
이슈번호 : #13

## TODO
- [ ] 패키지 설치
- [ ] settings.py 세팅
- [ ] 디폴트 사이트 설정 & admin세팅 
- [ ] 로그인 
- [ ] redirect 호출
- [ ] JWT 발급 받기
