### ISSUE TITLE
[Update] 채팅 기능 구조적 업그레이드 및 변경

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#152]
# 작업 내용
이슈번호 : #152

## TODO
- [x]  읽음 처리 기능 제거
- [x] 현재 채팅방에 접속중인 유저 중 상담이 진행중이지 않은 유저에 대하여 어드민에 표기
- [x] 원래 1명의 어드민 계정이 상담을 수행 햇으나 이제 늘어나도 지장이 생기지 않음.
