### ISSUE TITLE
백오피스 테스트코드 작성

### ISSUE THREAD

**Issue by Soeun-Jang** [Songjimyung/EcoCanvas-Backend#20]
# 작업 내용
이슈번호 : #20

## TODO
- [ ] 결제내역 월별 조회
- [ ] 펀딩 리스트 월별 내역 (성공/실패)
- [ ] 캠페인 신청 내역
- [ ] 캠페인 신청 승인/거부 기능
- [ ] shop 상품 등록
