### ISSUE TITLE
[Feature] Campaign 모델 개편, 검색기능

### ISSUE THREAD

**Issue by nueeng** [Songjimyung/EcoCanvas-Backend#234]
# 작업 내용
이슈번호 : #234

## TODO
- [ ] Campaign 모델 Category 추가
- [ ] Campaign 모델 taggit 추가
- [ ] Campaign 모델 검색기능 구현
