### ISSUE TITLE
[Enhancement] refresh 토큰 쿠키에 저장 및 자잘한 오류 수정

### ISSUE THREAD

**Issue by JooHan10** [Songjimyung/EcoCanvas-Backend#243]
# 작업 내용
이슈번호 : #243

## TODO
- [x] refresh 토큰 쿠키에 저장
- [x] 구글 소셜 로그인 로그인 타입 관련 오류 수정
- [x] 이메일 인증 부분 빈 문자열 표기 방식 수정
