### ISSUE TITLE
[Update] 실시간 채팅을 위한 상세기능 추가

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#26]
# 작업 내용
이슈번호 : #3 

## TODO
- [x]  채팅 관련 기능을 관리할 urls, views 추가
- [x] 소켓과 연결을 관리할 파일 생성
- [x] 소켓 연결을 중계 파일 생성
- [x] 소켓 통신 간 계정 인증을 처리할 미들웨어 생성
- [x] 테스트 코드 작성
