### ISSUE TITLE
[Feature] 유저 기본 모델 생성

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#4]
# 작업 내용
이슈번호 : #4

## TODO
- [x] 유저에 대한 기본적인 모델 생성
- [x] JWT를 이용한 로그인 및 회원가입 구현
- [x] 유저에 대한 설정 파일 수정
