### ISSUE TITLE
[Feature] 캠페인 기본 모델 생성

### ISSUE THREAD

**Issue by nueeng** [Songjimyung/EcoCanvas-Backend#5]
# 작업 내용
이슈번호 : #5

## TODO
- [x] 리뷰 모델 생성
- [x] 댓글 모델 생성
- [x] 펀딩 모델 생성
- [x] 좋아요 모델 생성(캠페인 안에 넣어도 좋을 것 같습니다)
