### ISSUE TITLE
[Update] 어드민 페이지를 위한 기능 추가

### ISSUE THREAD

**Issue by elan5027** [Songjimyung/EcoCanvas-Backend#57]
# 작업 내용
이슈번호 : #16

## TODO
- [x] 유저 시리얼라이저 추가
- [x] 일반 유저 전체 리스트 받아오는 기능 추가
- [x] 카테고리 받아오는 기능 추가
- [x] 전체 상품 목록 받아오는 기능 추가 
- [x] 카테고리 시리얼라이저 추가
