### ISSUE TITLE
[Test] 상품 테스트코드 추가 

### ISSUE THREAD

**Issue by Soeun-Jang** [Songjimyung/EcoCanvas-Backend#73]
# 작업 내용
이슈번호 : #73

## TODO
- [x] 상품등록 (다중이미지) 관리자/사용자 
- [x] 상품 쿼리매개변수별 조회, 검색어 조회, 상세 조회 
- [x] 상품 수정, 삭제 (+ 권한 테스트)
