### ISSUE TITLE
[Feature] 기본결제 추가, 결제 정보 확인 추가

### ISSUE THREAD

**Issue by Songjimyung** [Songjimyung/EcoCanvas-Backend#76]
# 작업 내용
이슈번호 :
#76

## TODO
- [x] 기본 결제 추가
- [x] 결제 정보 확인하기 추가
- [x] 기존 결제 모델 업데이트
