### ISSUE TITLE
[Fix] Campaign 리뷰, 댓글 시리얼라이저 수정

### ISSUE THREAD

**Issue by ghost** [Songjimyung/EcoCanvas-Backend#94]
# 작업 내용
이슈번호 :

## TODO
- [x] email대신 username(닉네임 or 주최자)으로 뜨도록 
- [x] 리뷰 시리얼라이저 유저 이메일 or 닉네임 보이도록 수정
- [x] 댓글 시리얼라이저 유저 이메일 or 닉네임 보이도록 수정
